version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "6590:9090"
    networks:
      - backend-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "6591:3000"
    networks:
      - backend-net

networks:
  backend-net:
    external: true